# Generated by Django 4.2.2 on 2023-06-13 15:46

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator
                        ],
                        verbose_name="username",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SU", "superuser"),
                            ("PUB", "publisher"),
                            ("CM", "content manager"),
                            ("CLN", "client"),
                        ],
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "Base User",
                "verbose_name_plural": "Base Users",
            },
        ),
    ]
