# Generated by Django 4.2.2 on 2023-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("SU", "superuser"),
                    ("PUB", "publisher"),
                    ("CM", "content manager"),
                    ("CLN", "client"),
                    ("UD", "undefined"),
                ],
                max_length=10,
                verbose_name="role",
            ),
        ),
    ]
