# Generated by Django 4.2.2 on 2023-06-15 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_publisher_contentmanager_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WFP", "waiting for publish"),
                            ("WFR", "waiting for review"),
                            ("RWFP", "reviewed and waiting for publish"),
                            ("P", "published"),
                            ("R", "rejected"),
                        ],
                        default="WFC",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creator",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="announcements",
                        to="accounts.contentmanager",
                        verbose_name="reviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
    ]
